[window]
edge=0
edge2=3
layer=3
is-layer-shell=1
transparent=1

[input]
keyboard="/dev/input/event4"

[xkb]
layout="de"
variant=""

[button.space]
sym="SPACE"
label="space"
y=-1
x=2
width=3
[button.3]
sym="shift_l|shift_r"
label="SHIFT"
x=-1
y=-1
[button.4]
sym="W"
y=1
x=2
width=3
[button.5]
sym="A"
x=2
[button.6]
sym="S"
x=3
[button.7]
sym="D"
x=4
