[window]
edge=0
edge2=3
layer=3


[input-device]
path="/dev/input/by-id/usb-Corsair_CORSAIR_K100_RGB_Optical-Mechanical_Gaming_Keyboard_F500190260075EF5AA0B8C640901303A-event-kbd"

[xkb]
layout="de"
variant=""



[buttons.space]
sym="SPACE"
label="space"
y=-1
x=2
width=3
[buttons.3]
sym="shift_l|shift_r"
label="SHIFT"
x=-1
y=-1
[buttons.4]
sym="W"
y=1
x=2
width=3
[buttons.5]
sym="A"
x=2
[buttons.6]
sym="S"
x=3
[buttons.7]
sym="D"
x=4